/**
 * Cortex Chat Server Router - v1 API Implementation
 * 
 * Express router for Cortex Agent API v1 with v2-compatible endpoints.
 * This router translates v1 responses to v2 format so the frontend doesn't need changes.
 * 
 * Key differences from v2:
 * - Requires inline agent specification (no Snowflake agent registry)
 * - Executes SQL queries generated by agent
 * - Implements custom thread management (in-memory)
 * - Translates all events to v2 format
 */

const express = require('express');
const { events } = require('fetch-event-stream');
const chatUtils = require('./chatUtils');
const v1History = require('./v1HistoryManager');
const v1Translator = require('./v1EventTranslator');
const v1SqlExecutor = require('./v1SqlExecutor');

/**
 * Create v1 chat router
 * @param {Object} config - Configuration object
 * @returns {express.Router} Configured Express router
 */
function createV1ChatRouter(config) {
  const router = express.Router();
  const { snowflakeHost, getAuthToken, getClaimsForRequest } = config;
  
  console.log('🔧 Creating v1 chat router');
  
  // =========================================================================
  // Helper Functions
  // =========================================================================
  
  /**
   * Get Snowflake authentication headers
   */
  const getSnowflakeAuthHeaders = (req) => {
    const token = getAuthToken(req);
    if (!token) {
      throw new Error('No authentication token provided');
    }
    return {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'Authorization': `Bearer ${token}`
    };
  };
  
  // =========================================================================
  // AGENT ROUTES
  // =========================================================================
  
  /**
   * GET /agents - List all agents (returns fixed agent in v1)
   */
  router.get('/agents', async (req, res) => {
    try {
      console.log('[v1] Listing agents (returning fixed agent)');
      return res.json(chatUtils.buildFakeAgentList(config));
    } catch (error) {
      console.error('[v1] Error listing agents:', error);
      res.status(500).json({ error: error.message });
    }
  });
  
  /**
   * GET /agents/:agentName - Get agent details
   */
  router.get('/agents/:agentName', async (req, res) => {
    try {
      const { agentName } = req.params;
      
      if (!chatUtils.validateAgentName(agentName)) {
        return res.status(400).json({ error: 'Invalid agent name' });
      }
      
      if (!chatUtils.isAgentAllowed(agentName, config)) {
        return res.status(403).json({ error: 'Agent not allowed' });
      }
      
      console.log(`[v1] Getting agent details for: ${agentName}`);
      return res.json(chatUtils.buildFakeAgentResponse(config));
    } catch (error) {
      console.error('[v1] Error getting agent details:', error);
      res.status(500).json({ error: error.message });
    }
  });
  
  /**
   * POST /agents/:agentName/messages - Send message to agent (streaming)
   * This is the core v1 message handler with SQL execution and event translation
   */
  router.post('/agents/:agentName/messages', async (req, res) => {
    try {
      const { agentName } = req.params;
      const { messages, thread_id, parent_message_id } = req.body;
      
      // Validation
      if (!chatUtils.validateAgentName(agentName)) {
        return res.status(400).json({ error: 'Invalid agent name' });
      }
      
      if (!chatUtils.isAgentAllowed(agentName, config)) {
        return res.status(403).json({ error: 'Agent not allowed' });
      }
      
      if (!Array.isArray(messages) || messages.length === 0) {
        return res.status(400).json({ error: 'messages array required' });
      }
      
      // Get session and claims
      const sessionId = chatUtils.getSessionId(req);
      if (!sessionId) {
        return res.status(401).json({ error: 'No session found' });
      }
      
      const claims = getClaimsForRequest(req);
      const authToken = getAuthToken(req);
      
      console.log(`[v1] Processing message for agent: ${agentName}, session: ${sessionId.substring(0, 8)}`);
      
      // Get or create thread
      let threadId = thread_id;
      if (!threadId) {
        threadId = v1History.createThread(sessionId);
        console.log(`[v1] Created new thread: ${threadId}`);
      }
      
      // Retrieve conversation history
      const thread = v1History.getThread(sessionId, threadId);
      if (!thread) {
        return res.status(404).json({ error: 'Thread not found' });
      }
      
      // Build full message history for v1 (needs entire conversation)
      const fullMessages = [
        ...thread.messages.map(m => ({ role: m.role, content: m.content })),
        ...messages
      ];
      
      console.log(`[v1] Full conversation: ${fullMessages.length} messages`);
      
      // Store user message
      const userMessage = messages[messages.length - 1];
      const userMessageId = v1History.addMessage(
        sessionId,
        threadId,
        userMessage.role,
        userMessage.content,
        parent_message_id || 0
      );
      
      // Build v1 request with inline spec
      const requestBody = chatUtils.mergeInlineSpec(config.agentSpec, {
        messages: fullMessages
      });
      
      // Setup SSE response
      res.setHeader('Content-Type', 'text/event-stream');
      res.setHeader('Cache-Control', 'no-cache');
      res.setHeader('Connection', 'keep-alive');
      res.setHeader('X-Accel-Buffering', 'no'); // Disable buffering for nginx
      
      const writeSSE = chatUtils.createSSEWriter(res);
      
      // Call Snowflake v1 Agent API
      console.log(`[v1] Calling agent API with ${fullMessages.length} messages`);
      const agentEndpoint = `https://${snowflakeHost}/api/v2/cortex/agent:run`;
      const agentResponse = await fetch(agentEndpoint, {
        method: 'POST',
        headers: {
          ...getSnowflakeAuthHeaders(req),
          'Accept': 'text/event-stream'
        },
        body: JSON.stringify(requestBody)
      });
      
      if (!agentResponse.ok) {
        const errorText = await agentResponse.text();
        console.error(`[v1] Agent API error: ${agentResponse.status} ${errorText}`);
        writeSSE('error', { error: 'Agent request failed', status: agentResponse.status, details: errorText });
        return res.end();
      }
      
      // Stream events and watch for SQL
      const agentEvents = events(agentResponse);
      let sqlDetected = false;
      const assistantMessageContent = [];
      
      for await (const event of agentEvents) {
        if (event.data === '[DONE]') {
          if (!sqlDetected) {
            writeSSE('done', '[DONE]');
          }
          break;
        }
        
        // Translate and forward event
        const isDone = v1Translator.translateEvent(event, writeSSE);
        if (isDone) break;
        
        // Parse event to check for SQL
        let payload;
        try {
          payload = JSON.parse(event.data || '{}');
        } catch {
          continue;
        }
        
        // Accumulate assistant message content (except sql_exec tool_use)
        if (payload?.delta?.content) {
          payload.delta.content.forEach(item => {
            if (item?.tool_use?.name !== 'sql_exec') {
              assistantMessageContent.push(item);
            }
          });
        }
        
        // Check for SQL in tool_results
        const sql = v1Translator.extractSQLFromPayload(payload);
        
        if (sql) {
          sqlDetected = true;
          console.log('[v1] SQL detected in response, executing...');
          
          try {
            // Emit thinking event
            v1Translator.emitThinkingEvent(writeSSE, 'Executing SQL query...');
            
            // Execute SQL
            const sqlResult = await v1SqlExecutor.executeSQL(
              `https://${snowflakeHost}`,
              authToken,
              sql,
              claims,
              config
            );
            
            // Emit SQL results to frontend
            writeSSE('sql_result', sqlResult);
            
            // Get statement handle
            const statementHandle = sqlResult.statementHandles?.at(-1) || sqlResult.statementHandle;
            
            // Build assistant message with tool results
            const assistantMessage = {
              role: 'assistant',
              content: assistantMessageContent
            };
            
            const sqlExecMessage = {
              role: 'user',
              content: [{
                type: 'tool_results',
                tool_results: {
                  name: 'sql_exec',
                  content: [{ type: 'json', json: { query_id: statementHandle } }]
                }
              }]
            };
            
            // Store assistant message (pre-SQL phase)
            const assistantMsgId1 = v1History.addMessage(sessionId, threadId, 'assistant', assistantMessageContent);
            
            // Store SQL execution as a "user" message (tool results)
            v1History.addMessage(sessionId, threadId, 'user', sqlExecMessage.content, assistantMsgId1);
            
            // Signal new assistant message phase
            writeSSE('new_assistant_message', { message: 'Processing SQL results...' });
            
            // Re-call agent with SQL results (data-to-analytics phase)
            const data2analyticsBody = chatUtils.mergeInlineSpec(config.agentSpec, {
              messages: [...fullMessages, assistantMessage, sqlExecMessage]
            });
            
            console.log('[v1] Calling agent API for data-to-analytics phase');
            const d2aResponse = await fetch(agentEndpoint, {
              method: 'POST',
              headers: {
                ...getSnowflakeAuthHeaders(req),
                'Accept': 'text/event-stream'
              },
              body: JSON.stringify(data2analyticsBody)
            });
            
            if (!d2aResponse.ok) {
              const errorText = await d2aResponse.text();
              console.error(`[v1] Data-to-analytics error: ${d2aResponse.status} ${errorText}`);
              writeSSE('error', { error: 'Data-to-analytics request failed', details: errorText });
              res.end();
              return;
            }
            
            // Stream data-to-analytics events
            const d2aEvents = events(d2aResponse);
            const d2aContent = [];
            
            for await (const d2aEvent of d2aEvents) {
              if (d2aEvent.data === '[DONE]') break;
              
              const isDone = v1Translator.translateEvent(d2aEvent, writeSSE);
              if (isDone) break;
              
              // Accumulate content
              try {
                const d2aPayload = JSON.parse(d2aEvent.data || '{}');
                if (d2aPayload?.delta?.content) {
                  d2aContent.push(...d2aPayload.delta.content);
                }
              } catch {}
            }
            
            // Store final assistant message
            if (d2aContent.length > 0) {
              const finalMessageId = v1History.addMessage(sessionId, threadId, 'assistant', d2aContent);
              v1Translator.emitMetadata(writeSSE, finalMessageId, threadId);
            }
            
            console.log('[v1] Data-to-analytics phase complete');
            
          } catch (sqlError) {
            console.error('[v1] SQL execution error:', sqlError);
            writeSSE('error', { error: sqlError.message, type: 'sql_execution_error' });
          }
          
          // Send done
          v1Translator.emitDone(writeSSE);
          res.end();
          return;
        }
      }
      
      // No SQL detected - store assistant message and complete
      if (!sqlDetected && assistantMessageContent.length > 0) {
        const assistantMessageId = v1History.addMessage(
          sessionId,
          threadId,
          'assistant',
          assistantMessageContent
        );
        v1Translator.emitMetadata(writeSSE, assistantMessageId, threadId);
        v1Translator.emitDone(writeSSE);
        console.log('[v1] Message complete (no SQL)');
      }
      
      res.end();
    } catch (error) {
      console.error('[v1] Error in message handler:', error);
      if (!res.headersSent) {
        res.status(500).json({ error: error.message });
      } else {
        try {
          const writeSSE = chatUtils.createSSEWriter(res);
          writeSSE('error', { error: error.message });
        } catch {}
        res.end();
      }
    }
  });
  
  // =========================================================================
  // THREAD ROUTES (using v1HistoryManager)
  // =========================================================================
  
  /**
   * POST /threads - Create new thread
   */
  router.post('/threads', async (req, res) => {
    try {
      const sessionId = chatUtils.getSessionId(req);
      if (!sessionId) {
        return res.status(401).json({ error: 'No session found' });
      }
      
      const threadId = v1History.createThread(sessionId, req.body?.origin_application);
      
      res.json({
        thread_id: threadId,
        origin_application: req.body?.origin_application,
        created_on: Date.now()
      });
    } catch (error) {
      console.error('[v1] Error creating thread:', error);
      res.status(500).json({ error: error.message });
    }
  });
  
  /**
   * GET /threads - List all threads
   */
  router.get('/threads', async (req, res) => {
    try {
      const sessionId = chatUtils.getSessionId(req);
      if (!sessionId) {
        return res.status(401).json({ error: 'No session found' });
      }
      
      const threads = v1History.listThreads(sessionId);
      res.json(threads);
    } catch (error) {
      console.error('[v1] Error listing threads:', error);
      res.status(500).json({ error: error.message });
    }
  });
  
  /**
   * GET /threads/:threadId - Get thread history
   */
  router.get('/threads/:threadId', async (req, res) => {
    try {
      const sessionId = chatUtils.getSessionId(req);
      if (!sessionId) {
        return res.status(401).json({ error: 'No session found' });
      }
      
      const { threadId } = req.params;
      
      const thread = v1History.getThread(sessionId, threadId);
      if (!thread) {
        return res.status(404).json({ error: 'Thread not found' });
      }
      
      res.json({
        metadata: {
          thread_id: thread.thread_id,
          thread_name: thread.thread_name,
          created_on: thread.created_on,
          updated_on: thread.updated_on
        },
        messages: thread.messages
      });
    } catch (error) {
      console.error('[v1] Error getting thread:', error);
      res.status(500).json({ error: error.message });
    }
  });
  
  /**
   * POST /threads/:threadId - Update thread name
   */
  router.post('/threads/:threadId', async (req, res) => {
    try {
      const sessionId = chatUtils.getSessionId(req);
      if (!sessionId) {
        return res.status(401).json({ error: 'No session found' });
      }
      
      const { threadId } = req.params;
      const { thread_name } = req.body;
      
      if (!thread_name) {
        return res.status(400).json({ error: 'thread_name required' });
      }
      
      v1History.updateThreadName(sessionId, threadId, thread_name);
      res.json({ success: true, thread_id: threadId, thread_name });
    } catch (error) {
      console.error('[v1] Error updating thread:', error);
      if (error.message.includes('not found')) {
        return res.status(404).json({ error: error.message });
      }
      res.status(500).json({ error: error.message });
    }
  });
  
  /**
   * DELETE /threads/:threadId - Delete thread
   */
  router.delete('/threads/:threadId', async (req, res) => {
    try {
      const sessionId = chatUtils.getSessionId(req);
      if (!sessionId) {
        return res.status(401).json({ error: 'No session found' });
      }
      
      const { threadId } = req.params;
      
      const deleted = v1History.deleteThread(sessionId, threadId);
      if (!deleted) {
        return res.status(404).json({ error: 'Thread not found' });
      }
      
      res.json({ success: true, thread_id: threadId });
    } catch (error) {
      console.error('[v1] Error deleting thread:', error);
      res.status(500).json({ error: error.message });
    }
  });
  
  return router;
}

module.exports = { createV1ChatRouter };

