/**
 * v1 SQL Executor
 * 
 * Executes SQL queries generated by v1 agent with optional session variable setting
 * for row-level security in hybrid PAT-OAUTH mode.
 */

// Statement parameters for consistent output formatting
const STATEMENT_PARAMETERS = {
  BINARY_OUTPUT_FORMAT: 'HEX',
  DATE_OUTPUT_FORMAT: 'YYYY-Mon-DD',
  TIME_OUTPUT_FORMAT: 'HH24:MI:SS',
  TIMESTAMP_NTZ_OUTPUT_FORMAT: 'YYYY-MM-DD HH24:MI:SS.FF3',
  TIMESTAMP_OUTPUT_FORMAT: 'YYYY-MM-DD HH24:MI:SS.FF3 TZHTZM',
  TIMEZONE: 'America/Los_Angeles',
  QUERY_TAG: 'cortex-agent-widget',
};

/**
 * Execute SQL with optional session variable setting
 * @param {string} snowflakeUrl - Snowflake base URL
 * @param {string} authToken - Snowflake access token
 * @param {string} sql - SQL query to execute
 * @param {Object} claims - OAuth claims (may be null)
 * @param {Object} config - Configuration object
 * @returns {Promise<Object>} SQL execution result
 * @throws {Error} If SQL execution fails
 */
async function executeSQL(snowflakeUrl, authToken, sql, claims, config) {
  // Build statement with session variable if hybrid mode enabled
  let statement = sql;
  
  if (config.SESSION_VAR_NAME && claims && config.CLAIM_KEY) {
    const userValue = claims[config.CLAIM_KEY];
    if (userValue) {
      // Escape single quotes in userValue
      const escapedValue = String(userValue).replace(/'/g, "''");
      // Use ALTER SESSION SET for setting session variables
      statement = `SET ${config.SESSION_VAR_NAME} = '${escapedValue}' ->> ${sql}`;
      // statement = `ALTER SESSION SET ${config.SESSION_VAR_NAME}='${escapedValue}'; ${sql}`;
      console.log(`[SQL] Setting session variable ${config.SESSION_VAR_NAME}=${escapedValue}`);
    } else {
      console.warn(`[SQL] Claim key '${config.CLAIM_KEY}' not found in claims, executing SQL without session variable`);
    }
  }
  
  const requestBody = {
    statement: statement,
    warehouse: config.SNOWFLAKE_WAREHOUSE,
    parameters: STATEMENT_PARAMETERS
  };
  
  // Log SQL execution (truncate for readability)
  const sqlPreview = statement.length > 100 ? statement.substring(0, 100) + '...' : statement;
  console.log(`[SQL] Executing: ${sqlPreview}`);
  
  const response = await fetch(`${snowflakeUrl}/api/v2/statements`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${authToken}`
    },
    body: JSON.stringify(requestBody)
  });
  
  if (!response.ok) {
    const errorText = await response.text();
    console.error(`[SQL] Execution failed: ${response.status} ${errorText}`);
    throw new Error(`SQL execution failed: ${response.statusText}`);
  }
  
  const result = await response.json();
  const statementHandle = result.statementHandles?.at(-1) || result.statementHandle;
  console.log(`[SQL] Execution complete, statementHandle: ${statementHandle}`);
  
  return result;
}

module.exports = { executeSQL };

